plugins {
    id 'pagodividido.android.library'
    id 'pagodividido.android.hilt'
}

android {
    namespace 'com.anwera97.infra'

    defaultConfig {
        targetSdk 35
    }
}

dependencies {
    implementation project(':domain')
    implementation project(':data')


    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso.core
}
