plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.hilt)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
}

android {
    compileSdk 35
    defaultConfig {
        applicationId "com.anwera64.pagodividido"
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.anwera64.pagodividido'
    buildFeatures {
        compose true
    }
    lint {
        abortOnError false
    }
}

dependencies {
    implementation project(':domain')
    implementation project(':infra')
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.legacy.support
    implementation libs.androidx.cardview
    implementation libs.androidx.recyclerview

    // Lifecycle
    implementation libs.bundles.lifecycle
    testImplementation libs.androidx.arch.core.testing

    // Coroutines
    api libs.kotlinx.coroutines.core
    api libs.kotlinx.coroutines.android

    // KTX
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.fragment.ktx

    // Navigation
    implementation libs.bundles.navigation

    // Hilt
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    // Compose
    implementation platform(libs.compose.bom)
    androidTestImplementation platform(libs.compose.bom)
    implementation libs.compose.material3
    implementation libs.compose.ui.tooling.preview
    debugImplementation libs.compose.ui.tooling
    implementation libs.androidx.activity.compose
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.compose.runtime.livedata

    testImplementation libs.junit
    androidTestImplementation libs.bundles.android.test
    androidTestImplementation libs.androidx.navigation.testing
}
