plugins {
    id 'pagodividido.android.library'
    id 'pagodividido.android.hilt'
    id 'pagodividido.android.compose'
}

android {
    namespace 'com.anwera97.pagodividido'
    lint {
        abortOnError false
    }
}

dependencies {
    implementation project(':domain')
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.legacy.support
    implementation libs.androidx.cardview
    implementation libs.androidx.recyclerview

    // Lifecycle
    implementation libs.bundles.lifecycle
    testImplementation libs.androidx.arch.core.testing

    // Coroutines
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    // KTX
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.fragment.ktx

    // Navigation
    implementation libs.bundles.navigation


    // Compose
    implementation platform(libs.compose.bom)
    androidTestImplementation platform(libs.compose.bom)
    implementation libs.compose.material3
    implementation libs.compose.ui.tooling.preview
    debugImplementation libs.compose.ui.tooling
    implementation libs.androidx.activity.compose
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.compose.runtime.livedata

    testImplementation libs.junit
    androidTestImplementation libs.bundles.android.test
    androidTestImplementation libs.androidx.navigation.testing
}
