plugins {
    id 'pagodividido.android.library'
}

android {
    namespace 'com.anwera97.domain'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.javax.inject
    implementation libs.kotlinx.coroutines.core


    testImplementation libs.junit
    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin
    testImplementation libs.kotlinx.coroutines.test
}
