plugins {
    id 'anwera97.android.library'
    id 'anwera97.android.hilt'
}

android {
    namespace 'com.anwera97.domain'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])


    testImplementation libs.junit
    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin
    testImplementation libs.kotlinx.coroutines.test
}
