plugins {
    id 'pagodividido.android.library'
    id 'pagodividido.android.hilt'
}

android {
    namespace 'com.anwera97.data'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':domain')

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat

    // Room
    implementation libs.bundles.room
    ksp libs.androidx.room.compiler
    testImplementation libs.androidx.room.testing

    // Coroutines
    implementation libs.bundles.coroutines


    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso.core
}
